import { suite, test } from 'mocha';
import { expect } from 'chai';
import * as fs from 'fs';
import * as path from 'path';
import { planDualBankArtifacts } from '../../../dualBank/generate';
import { resolveBootloader, parseBootloaderConfig } from '../../../dualBank/config';

// The compiled test runs from out/test/unit/dualBank/, but `tsc` does not copy
// non-.ts fixtures into out/. Resolve fixtures from the src/ tree instead:
// out/test/unit/dualBank -> ../../../../ == repo root -> src/test/fixtures/dualBank
const fixt = (name: string): string =>
  fs.readFileSync(path.resolve(__dirname, '../../../../src/test/fixtures/dualBank', name), 'utf8');

const base = fixt('base.STM32L432XX_FLASH.ld');
const resolved = resolveBootloader(parseBootloaderConfig(
  'bootloader:\n  preset: stm32l432-can-bootloader\n  targetBaseName: HVC\n'
  + '  commonDefs: [STM32L432xx, USE_HAL_DRIVER]\n',
)!);

suite('generate dual-bank artifacts', () => {
  test('plans one linker script per bank with a sentinel header', () => {
    const r = planDualBankArtifacts({
      version: '0.1.0', baseLinkerScript: base, baseLinkerScriptRelPath: 'STM32L432XX_FLASH.ld',
      resolved, existingFiles: [],
    });
    expect(r.files.map((f) => f.relPath)).to.deep.equal([
      'linker/STM32L432XX_APP_BANK_A.ld',
      'linker/STM32L432XX_APP_BANK_B.ld',
    ]);
    expect(r.files[0].content).to.contain('GENERATED by stm32-trev 0.1.0');
    expect(r.files[0].content).to.contain('ORIGIN = 0x08008000, LENGTH = 104K');
    expect(r.files[1].content).to.contain('ORIGIN = 0x08022000, LENGTH = 104K');
    expect(r.files.every((f) => f.handEdited === false)).to.equal(true);
    expect(r.bankLdRelPaths.a).to.equal('linker/STM32L432XX_APP_BANK_A.ld');
  });

  test('does not flag an untouched generated file even when the base script changed', () => {
    const first = planDualBankArtifacts({
      version: '0.1.0', baseLinkerScript: base, baseLinkerScriptRelPath: 'STM32L432XX_FLASH.ld',
      resolved, existingFiles: [],
    });
    // Simulate: nothing touched the file since it was written; only the base .ld changed
    // (e.g. a CubeMX regen) before this second planning pass.
    const second = planDualBankArtifacts({
      version: '0.1.0', baseLinkerScript: base + '\n/* changed base */',
      baseLinkerScriptRelPath: 'STM32L432XX_FLASH.ld',
      resolved,
      existingFiles: [{ relPath: 'linker/STM32L432XX_APP_BANK_A.ld', content: first.files[0].content }],
    });
    expect(second.files[0].handEdited).to.equal(false);
    // Sanity check that the file actually did regenerate with the new inputs.
    expect(second.files[0].content).to.not.equal(first.files[0].content);
  });

  test('flags a file the user edited, even when the inputs are unchanged', () => {
    const first = planDualBankArtifacts({
      version: '0.1.0', baseLinkerScript: base, baseLinkerScriptRelPath: 'STM32L432XX_FLASH.ld',
      resolved, existingFiles: [],
    });
    const tampered = first.files[0].content + '\n/* a human tweak */';
    const second = planDualBankArtifacts({
      version: '0.1.0', baseLinkerScript: base, baseLinkerScriptRelPath: 'STM32L432XX_FLASH.ld',
      resolved,
      existingFiles: [{ relPath: 'linker/STM32L432XX_APP_BANK_A.ld', content: tampered }],
    });
    expect(second.files[0].handEdited).to.equal(true);
  });
});
