import { suite, test } from 'mocha';
import { expect } from 'chai';
import {
  hashInputs, buildSentinelHeader, extractInputsHash, isGenerated, isHandEdited, stripSentinelHeader,
} from '../../../dualBank/sentinel';

suite('sentinel', () => {
  test('hashInputs is stable and order-sensitive', () => {
    expect(hashInputs(['a', 'b'])).to.equal(hashInputs(['a', 'b']));
    expect(hashInputs(['a', 'b'])).to.not.equal(hashInputs(['b', 'a']));
    expect(hashInputs(['x'])).to.match(/^[0-9a-f]{64}$/);
  });

  test('a built header round-trips through extractInputsHash', () => {
    const h = hashInputs(['linker', 'config']);
    const header = buildSentinelHeader('#', '0.1.0', h);
    expect(header.startsWith('# GENERATED by stm32-trev 0.1.0')).to.equal(true);
    expect(extractInputsHash(header)).to.equal(h);
    expect(isGenerated(header + 'body')).to.equal(true);
  });

  test('isGenerated is false for a plain file', () => {
    expect(isGenerated('MEMORY { }')).to.equal(false);
    expect(extractInputsHash('nothing here')).to.equal(undefined);
  });

  test('stripSentinelHeader recovers the exact body for a line-comment header', () => {
    const body = 'first line\nsecond line\n';
    const header = buildSentinelHeader('#', '0.1.0', hashInputs([body]));
    expect(stripSentinelHeader(header + body)).to.equal(body);
  });

  test('stripSentinelHeader recovers the exact body for a block-comment header', () => {
    const body = 'MEMORY\n{\n}\n';
    const header = buildSentinelHeader('/*', '0.1.0', hashInputs([body]));
    expect(stripSentinelHeader(header + body)).to.equal(body);
  });

  test('stripSentinelHeader returns the input unchanged when there is no sentinel', () => {
    expect(stripSentinelHeader('plain file, no header')).to.equal('plain file, no header');
  });

  test('isHandEdited is false when the recorded hash matches the current body', () => {
    const body = 'MEMORY { }';
    const header = buildSentinelHeader('#', '0.1.0', hashInputs([body]));
    expect(isHandEdited(header + body)).to.equal(false);
  });

  test('isHandEdited is true when the current body no longer matches the recorded hash', () => {
    const body = 'MEMORY { }';
    const header = buildSentinelHeader('#', '0.1.0', hashInputs([body]));
    const tampered = header + body + '\n/* a human edit */';
    expect(isHandEdited(tampered)).to.equal(true);
  });

  test('isHandEdited is false for a plain (non-generated) file', () => {
    expect(isHandEdited('plain file')).to.equal(false);
  });

  test('buildSentinelHeader emits a valid C block comment for the "/*" prefix', () => {
    const header = buildSentinelHeader('/*', '0.1.0', hashInputs(['ld']));
    expect(header.startsWith('/*')).to.equal(true);
    expect(header).to.contain('* GENERATED by stm32-trev 0.1.0');
    expect(header).to.contain(' */');
  });

  test('extractInputsHash round-trips the block-comment header', () => {
    const h = hashInputs(['ld', 'cfg']);
    const header = buildSentinelHeader('/*', '0.1.0', h);
    expect(extractInputsHash(header)).to.equal(h);
  });

  test('isGenerated is true for a block-comment header followed by a body', () => {
    const header = buildSentinelHeader('/*', '0.1.0', hashInputs(['ld']));
    expect(isGenerated(header + 'MEMORY { }')).to.equal(true);
  });

  test('isHandEdited works on the block-comment header', () => {
    const body = 'MEMORY { }';
    const header = buildSentinelHeader('/*', '0.1.0', hashInputs([body]));
    expect(isHandEdited(header + body)).to.equal(false);
    expect(isHandEdited(header + body + ' /* tweak */')).to.equal(true);
  });
});
