/**
* MIT License
*
* Copyright (c) 2020 Bureau Moeilijke Dingen
* 
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
* 
* The above copyright notice and this permission notice shall be included in all
* copies or substantial portions of the Software.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*/

import { createHash } from 'crypto';

const HASH_MARKER = 'stm32-trev-inputs-sha256:';
const GENERATED_MARKER = 'GENERATED by stm32-trev';

/** sha256 hex digest of `parts` joined by a NUL byte. Order-sensitive. */
export function hashInputs(parts: string[]): string {
  return createHash('sha256').update(parts.join('\0')).digest('hex');
}

/**
 * Build the "do not edit" sentinel header that prefixes every generated build file.
 *
 * For `commentPrefix === '/*'` a valid C / GNU-ld block comment is emitted, because
 * `#` is not legal linker-script syntax. Every other prefix (`#`, `//`) keeps the
 * per-line form. Both forms carry the `GENERATED by stm32-trev` and
 * `stm32-trev-inputs-sha256:` markers and end with a blank line.
 */
export function buildSentinelHeader(commentPrefix: string, version: string, inputsHash: string): string {
  const lines = [
    `${GENERATED_MARKER} ${version} — do not edit.`,
    'Re-run "STM32 TREV: Regenerate Build Files" after changing the CubeMX project or bootloader config.',
    `${HASH_MARKER} ${inputsHash}`,
  ];
  if (commentPrefix === '/*') {
    return `${['/*', ...lines.map((line) => ` * ${line}`), ' */'].join('\n')}\n\n`;
  }
  return `${lines.map((line) => `${commentPrefix} ${line}`).join('\n')}\n\n`;
}

/** The recorded inputs hash from a sentinel header, or `undefined` if none is present. */
export function extractInputsHash(fileContent: string): string | undefined {
  const match = fileContent.match(new RegExp(`${HASH_MARKER}\\s*([0-9a-f]{64})`));
  return match ? match[1] : undefined;
}

/**
 * Returns the body of a generated file — everything after the sentinel header.
 * The header always ends with a blank line immediately following the line that
 * carries the inputs-hash marker (in both line-comment and block-comment form),
 * so locating that blank line locates the header/body boundary reliably.
 * Returns the whole input unchanged if no sentinel header is found.
 */
export function stripSentinelHeader(fileContent: string): string {
  const match = fileContent.match(new RegExp(`${HASH_MARKER}\\s*[0-9a-f]{64}`));
  if (!match || match.index === undefined) { return fileContent; }
  const boundary = fileContent.indexOf('\n\n', match.index);
  if (boundary === -1) { return fileContent; }
  return fileContent.slice(boundary + 2);
}

/** True when `fileContent` carries a stm32-trev sentinel header. */
export function isGenerated(fileContent: string): boolean {
  return fileContent.includes(GENERATED_MARKER) && extractInputsHash(fileContent) !== undefined;
}

/**
 * True when `fileContent` is a stm32-trev generated file whose current on-disk
 * body no longer hashes to what its own header recorded — i.e. someone edited it
 * after generation. This is independent of whether the inputs that would be used
 * to regenerate the file have changed; it only asks "did the content drift from
 * what was last written here".
 */
export function isHandEdited(fileContent: string): boolean {
  if (!isGenerated(fileContent)) { return false; }
  const recorded = extractInputsHash(fileContent);
  const actual = hashInputs([stripSentinelHeader(fileContent)]);
  return recorded !== actual;
}
